spring:
  application:
    name: bff-restaurante

clients:
  ms-usuarios:
    url: ${MS_USUARIOS_URL:http://localhost:8081}
  ms-mesas:
    url: ${MS_MESAS_URL:http://localhost:8082}
  ms-pedidos:
    url: ${MS_PEDIDOS_URL:http://localhost:8083}
  ms-produtos:
    url: ${MS_PRODUTOS_URL:http://localhost:8084}
  ms-notificacoes:
    url: ${MS_NOTIFICACOES_URL:http://localhost:8085}

jwt:
  secret: ${JWT_SECRET:chave-super-secreta-para-jwt-local-fourkitchen-123456789}
