spring:
  application:
    name: bff-restaurante
  cloud:
    openfeign:
      httpclient:
        hc5:
          enabled: true
      client:
        config:
          ms-mesas:
            connectTimeout: 2000
            readTimeout: 4000
          ms-pedidos:
            connectTimeout: 2000
            readTimeout: 300000

clients:
  ms-usuarios:
    url: ${MS_USUARIOS_URL:http://localhost:8081}
  ms-mesas:
    url: ${MS_MESAS_URL:http://localhost:8082}
  ms-pedidos:
    url: ${MS_PEDIDOS_URL:http://localhost:8083}
  ms-produtos:
    url: ${MS_PRODUTOS_URL:http://localhost:8084}
  ms-notificacoes:
    url: ${MS_NOTIFICACOES_URL:http://localhost:8085}
  ms-pagamentos:
    url: ${MS_PAGAMENTOS_URL:http://localhost:8087}

server:
  port: ${SERVER_PORT:8080}

jwt:
  secret: ${JWT_SECRET}

websocket:
  allowed-origins: ${WEBSOCKET_ALLOWED_ORIGINS:http://localhost:4200}
  heartbeat-ms: ${WEBSOCKET_HEARTBEAT_MS:10000}
