package br.com.fourkitchen.bff_restaurante.realtime;

public enum RealtimeEventType {
    PEDIDO_CRIADO,
    PEDIDO_EM_PREPARO,
    PEDIDO_PRONTO,
    PEDIDO_ENTREGUE,
    PEDIDO_CANCELADO,
    PEDIDO_PROBLEMA_SINALIZADO,
    PEDIDO_PROBLEMA_RESOLVIDO,
    MESA_ABERTA,
    MESA_FECHADA,
    GARCOM_ATRIBUIDO,
    CHAMADA_GARCOM_CRIADA,
    CHAMADA_GARCOM_CONCLUIDA,
    PRODUTO_ALTERADO,
    CATEGORIA_ALTERADA,
    USUARIO_ALTERADO
}
