spring:
  application:
    name: ms-mesas
  datasource:
    hikari:
      maximum-pool-size: 2
      minimum-idle: 1
server:
  port: ${SERVER_PORT:8082}

clients:
  ms-pedidos:
    url: ${MS_PEDIDOS_URL:http://localhost:8083}
